### ISSUE TITLE
Content foutje

### ISSUE THREAD

**Issue by jbblesch** [gumbo-millennium/website#104]
Geachte,
De wekelijkse mail met de wjd'jes en quotes naar de Gumbode eindigt op:
"je ontvangt deze mail omdat je in de PRPG zit, afmelden voor deze mails kan niet".
Gumbode != PRPG.

Bijgevoegd een screenshot:
[Knipsel](https://user-images.githubusercontent.com/63496044/82184178-7c63bd00-98e7-11ea-9f85-888e0e62f70d.JPG)

Met vriendelijke groet,
Jan-Bate Bles

**Comment by roelofr** [comment]
Pfft
