### ISSUE TITLE
Sponsor logo inconsistency

### ISSUE THREAD

**Issue by Semprosx** [gumbo-millennium/website#109]
1. Inconsistent usage of monochrome and color logos.
2. Sponsor logos without detail page should link directly to the sponsor url, not to the non-existent detail page.
![image](https://user-images.githubusercontent.com/46891201/84161891-0c70ce80-aa70-11ea-8747-597cbb7e7ca6.png)

**Comment by Semprosx** [comment]
Logo color shift on mouse over is not available when the browsers is in dark mode. Maybe make this a fade into a lighter color?

**Comment by roelofr** [comment]
Please provide more details and examples for issues 1 and 2. Where are the inconsencies? What sponsors redirect or link incorrectly?

Dark mode isn't as thoroughly tested as light mode, as less shades are available
