### ISSUE TITLE
Not possible to view subscribers

### ISSUE THREAD

**Issue by jbblesch** [gumbo-millennium/website#112]
Hello,
As discussed through Telegram:

On the first event I can view and edit the subscriptions. With the second event, which has 5 subscribers, I can't even see them on the adminpanel:  

![](https://i.imgur.com/vke9hv1.png)

Your's truly,
J. B. Bles

**Comment by markwalet** [comment]
@roelofr Weet je al waardoor dit komt? Of nog geen idee?

Zo niet, geef me een prod db kopie en ik kijk zelf even.

**Comment by roelofr** [comment]
Komt uit Nova zelf, en je ziet het ook als je als LHW inlogt na te clonen en te seeden

**Comment by roelofr** [comment]
A fix for this issue is in 723a2c8e51a4632a0701d1106a00555722d1cfa0.
