### ISSUE TITLE
Add text input for 'referred by' to the membership application form.

### ISSUE THREAD

**Issue by Semprosx** [gumbo-millennium/website#113]
Add an input where applicants can give information on how they came into contact with Gumbo.

**Comment by roelofr** [comment]
Why? It makes the already rather long form even longer

**Comment by Semprosx** [comment]
To be able to determine the effectiveness of our social media and other recruitment campaigns. Also, when they were referred to Gubmo by another member we need to be able to know who this person is for a referral bonus.

**Comment by roelofr** [comment]
Fixed in 59a83da1275ec2cd3cc71f378f11b001d86da61d
