### ISSUE TITLE
"Alleen leden" activities throw a 403 for non-members

### ISSUE THREAD

**Issue by roelofr** [gumbo-millennium/website#123]
When you're not a member, but visit a member-only activity, you get an "Access denied" page.

As these activities aren't necessarily secret. but just exclusively for members, this page should be different. Something that doesn't give away the date or location, but informs the user that the activity exists for members only.

The [`DisplayController`][1] already takes non-member activities into account by throwing a custom 403 (and a 403 is the right status code), which should be replaced with a simple "This activity is for members only.

[1]: https://github.com/gumbo-millennium/website/blob/master/app/Http/Controllers/Activities/DisplayController.php#L107

## Test case

Expected behaviour: A "this activity is for members only" page is shown when a non-member visits the activity

Current behaviour: The user is shown a 403 with little to no explanation.

## Local test case

After seeding the database (`php artisan migrate:fresh --seed`), log in (`/auth/login`) as the Guest user, and visit the Private Paid activity (`/activities/private-paid`). This activity is for members only.

## Hacktoberfest 🎃

Since this is a small change and a good try-out with Laravel, this issue is destined for Hacktoberfest. Contributions are more than welcome.

**Comment by Rocksheep** [comment]
Is it alright if I grab this issue?

**Comment by Rocksheep** [comment]
It seems like I need a laravel/nova token. Can I receive one to develop this feature for you?

**Comment by roelofr** [comment]
Hello @Rocksheep, you're more than welcome to pick up this issue.

Do you have your own token for Laravel Nova, or should I include you in the request posted in [#124](https://github.com/gumbo-millennium/website/issues/124#issuecomment-701586516)?

**Comment by Rocksheep** [comment]
I don't have my own token, so it would be nice if you could include me.

**Comment by roelofr** [comment]
Okay, an update: I've changed the code to no longer require Laravel Nova and a local dummy package is now included in the application.

You should be fine without a token.

**Comment by pedroxido** [comment]
@roelofr I'm having a bit of issues while running `composer run contribute`. 

`> @php artisan app:env

In ProviderRepository.php line 208:
                                                          
  Class 'TheCodingMachine\Discovery\Discovery' not found  
                                                          

Script @php artisan app:env handling the contribute event returned with error code 1
`

All dependencies were installed without errors, and when I go to the ProviderRepository.php I'm able to find the Discovery.php  class and the import looks ok, is there something that i'm missing? Have you encountered this issue in the past?
