### ISSUE TITLE
Show available places in `/activiteiten` bot command

### ISSUE THREAD

**Issue by roelofr** [gumbo-millennium/website#124]
Currently, the `/activiteiten` command in Botman shows when an activity is cancelled and sold out, but does not show how many places are left for the activity.

We would like the `ActivityMessage` to show this, and all data is already available for this.

## Test case

Expected behaviour: The [Gumbobot][1] on Telegram shows the number of available places for an activity, if it's not yet sold out:

> Activiteiten 🎯
>
> 14-10 | Intro 2020 (€ 35,29, 26 / 40 plekken)
>
> Voor meer info, check de site of het activiteitenkanaal

Current behaviour: The number of available places is not shown:

> Activiteiten 🎯
>
> 14-10 | Intro 2020 (€ 35,29)
>
> Voor meer info, check de site of het activiteitenkanaal

[1]: https://telegram.me/gumbobot

## Local testing

You can use the `botman:tinker` command to test commands locally.

## Hacktoberfest 🎃

Since this is a small change and a good try-out with Laravel, this issue is destined for Hacktoberfest. Contributions are more than welcome.

**Comment by pedroxido** [comment]
hey @roelofr, I'd like to work on this as part of the hacktoberfest, I was reviewing the contributing.md and it looks like I will need a login/password/token to start using this project, is there a way that you can provide a development token for me to try it out?

**Comment by roelofr** [comment]
Hello @pedroxido, thank you for your interest in this issue.

I'll have to reach out to the guys at Laravel Nova about granting access for FOSS purposes. I can shove a "don't share the token" agreement to memmbers of the student community this project belongs to, but for you I'll have to double check before Taylor sends an army of lawyers my way for no good reason.

I'll get back to you.

**Comment by roelofr** [comment]
Okay, an update: I've changed the code to no longer require Laravel Nova and a local dummy package is now included in the application.

You should be fine without a token.

**Comment by roelofr** [comment]
Hello @pedroxido, thank you for reporting this. I've looked into it and it's absolutely a repo-wide problem.

I've fixed the commands, so `composer run contribute` should now work as intended, and added automated tests that should catch these issues in the future.

**Comment by pedroxido** [comment]
Hi @roelofr thanks for the help! I was able to get the project running locally

**Comment by roelofr** [comment]
Glad to hear that. Feel free to work on that PR at your own pace. Let me know if anything is unclear.
