### ISSUE TITLE
Blank target for sponsoring

### ISSUE THREAD

**Issue by markwalet** [gumbo-millennium/website#136]
On pages like this: https://www.gumbo-millennium.nl/sponsoren/rysst

The "Read more" button should have a `target="_blank"` attribute. This is expected behaviour when you go to an external website.

**Comment by sama11y** [comment]
``https://github.com/gumbo-millennium/website/issues/136#issue-734934265

**Comment by sama11y** [comment]
> On pages like this: https://www.gumbo-millennium.nl/sponsoren/rysst
> 
> The "Read more" button should have a `target="_blank"` attribute. This is expected behaviour when you go to an external website.
