### ISSUE TITLE
Subcategorie ondersteuning in bestandsysteem

### ISSUE THREAD

**Issue by roelofr** [gumbo-millennium/website#17]
Nieuwe property: `parent_id` met een many-to-one relationship.

**Comment by Semprosx** [comment]
Deze categorieën moeten functioneel gelijk zijn aan parent folders.

**Comment by roelofr** [comment]
Stel je hebt deze structuur
```
.
├── alv
└── notulen-oud
    ├── 2018-11-01
    │   └── notulen.pdf
    └── readme.pdf
```

Je wil de categorie `notulen-oud` verwijderen, wat gebeurt er met de bestanden en categorieën in deze map?

**Comment by Semprosx** [comment]
Een optie is om alle onderliggende items te verwijderen. Dit is snel maar wel foutgevoeliger en ingrijpender zodra er een fout gemaakt wordt. Wel kan is het een tijdrovend wanneer de hele structuur gewijzigd wordt.

Kunnen we de gebruiker een overzicht van onderliggende items geven zodra hij een map wil verwijderen, waarna de gebruiker zelf kan kiezen of hij alles een map omhoog wil verplaatsen (of naar default als het al een root is) of dat hij alle items wilt verwijderen?

**Comment by roelofr** [comment]
Alternatief: linux werkt met een 'lost+found' map, waarin alle bestanden die geen 'parent' map hebben, belanden. Ik kan ook een systeem maken dat bestanden zonder 'parent' categorie, daar gewoon belanden.

-------- Original Message --------

**Comment by Semprosx** [comment]
Dit lijkt me een prima alternatief.
