### ISSUE TITLE
WervingCommissie Leaderboard

### ISSUE THREAD

**Issue by BasbrandiusMaximus** [gumbo-millennium/website#181]
Leuke user story: "Als wervingscommissie willen we een leaderboard van wie wie bij de vereniging heeft gesleept om mensen competitief te maken om bij Gumbo te krijgen"

het idee is om een command in de GumBot in te bouwen waarmee een leaderboard opgevraagd kan worden.
We willen dat dit automatisch wordt aangevuld wanneer iemand zich inschrijft voor Gumbo via de site.
Als het verzameld wordt in een aparte database met zo min mogelijk informatie(want AVG) dan kunnen we dat zelf makkelijk bijhouden. Toegang naar de database moet natuurlijk beveiligd zijn met bijvoorbeeld een WC-account.
We willen ook handmatig inschrijvingen kunnen toevoegen na mensen binnenslepen uit open-dagen

Als de hele DB-lijst in een query op volgorde in een array opgevraagd kan worden dan hoeft het alleen op volgorde getoond te worden. Iets makkelijks zoals:

```sql
SELECT Aanrader, COUNT(*) 
FROM Table 
WHERE Aanrader IS NOT NULL 
GROUP BY Aanrader 
ORDER BY COUNT(*)
```

Om te verzekeren dat iemand toestemming geeft om op de leaderboard te komen kan een voorkeur/optie bij het Gumbo-account  worden toegevoegd. Met een makkelijk vinkje kan je dan om toestemming vragen.

Opmaak: Iets simpels met een limiet van ongeveer 10 om het overzichtelijk te houden.
`/leaderboard`.

> Gumboërs met de meeste leden binnengehaald:
> 
> 🥇 1. Denise - 10
> 🥈 2. Mark - 5
> 🥉 3. Bastian - 3
> 4. ???(not opt in) - 2
> 5. Roelof - 1
> 6. Jelle - 1
> Sta je er niet? Verander dan je voorkeur bij je Gumbo account.
----------------------------------------------------

**Comment by roelofr** [comment]
Features to develop

- [ ] `JoinSuggestion` model
- [ ] `JoinSuggestion` Nova resource
- [ ] `/leaderboard` command, members only
- [ ] Patching in on `JoinSubmission` creation
- [ ] Add new "my preferences" view to my account
- [ ] Add opt-in for leaderboard.
