### ISSUE TITLE
Login page redirects to /admin when logged in

### ISSUE THREAD

**Issue by roelofr** [gumbo-millennium/website#80]
It should check if we can actually redirect someone there first.

**Comment by shirshak55** [comment]
What do this mean? Nova config.php already has /admin so if u go to /admin you should see login page right?

**Comment by roelofr** [comment]
Yep, but sometimes users who aren't allowed to access the admin (are rejected by the Nova Gate) are still sent there and shown a beautiful 403. Those users should just be sent home or something.

**Comment by shirshak55** [comment]
@roelofr Then we can change redirect link instead of 403.

**Comment by roelofr** [comment]
Well, yeah, but I haven't had time for that so I made an issue.

**Comment by shirshak55** [comment]
Logic u are searching can be found here `Laravel\Nova\Http\Middleware` It should be authenticate & authorized middleware.

**Comment by roelofr** [comment]
You mean in [`App\\Http\\Middleware\\RedirectIfAuthenticated`](https://github.com/gumbo-millennium/website/blob/b1a6e65f6d40c839f82ee7c92ef16568d7146a9f/app/Http/Middleware/RedirectIfAuthenticated.php#L20) right?

**Comment by shirshak55** [comment]
Yes it should be.

**Comment by markwalet** [comment]
I think the middleware expansion is not the only thing you should do.

We should also change the `LoginController@redirectRoute()`(?) method.
